img_dir: data/0929_dataset/
val_ratio: 0.05
batch_size: 32
max_dataset_size: -1
n_epochs: 1000
shuffle: 1
print_freq: 10
val_freq: 20
chkpt_freq: 20
starting_epoch: 0
normalize_type: null
iter_per_epoch: 50

model:
  lr: 0.00001
  lr_policy: step
  lr_decay_period: -1
  lr_decay_ratio: 0.2
  lambda_recon: 100
  D_update_interval: 5
  img_size: 256
  n_channels: 1
  warm_up: 0